import type { Metadata } from "next";
import { Geist, Geist_Mono, Just_Another_Hand } from "next/font/google";
import "./globals.css";

const justAnotherHand = Just_Another_Hand({
  variable: "--font-just-another-hand",
  weight: "400",
  subsets: ["latin"],
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${justAnotherHand.className} antialiased bg-gray-100`}>
        {children}
      </body>
    </html>
  );
}
